name: Publish Geosite data

on:
  workflow_dispatch:
  schedule:
    - cron: '0 22 * * *'

env:
  GEOSITE_SOURCE_REPO: 'v2fly/domain-list-community'
  GEOSITE_SOURCE_GIT_REF: 'master'
  SINGBOX_SOURCE_REPO: 'sagernet/sing-box'
  SINGBOX_VER: '1.9.1'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          path: './'

      - name: Prepare
        run: |
          mkdir -p ${{ github.workspace }}/dist
          mkdir -p ${{ github.workspace }}/upload
          echo "TAG_NAME=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      - name: Checkout ${{ env.GEOSITE_SOURCE_REPO }} Source code
        uses: actions/checkout@v4
        with:
          repository: ${{ env.GEOSITE_SOURCE_REPO }}
          fetch-depth: 1
          ref: ${{ env.GEOSITE_SOURCE_GIT_REF }}
          path: './domain-list-community'

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.22'
          check-latest: true

      - name: Download sing-box
        run: |
          cd ${{ github.workspace }}
          curl --connect-timeout 5 --retry 5 --retry-delay 5 --retry-max-time 25 -sLo sing-box.tar.gz https://github.com/${{ env.SINGBOX_SOURCE_REPO }}/releases/download/v${{ env.SINGBOX_VER }}/sing-box-${{ env.SINGBOX_VER }}-linux-amd64v3.tar.gz
          tar xzvf sing-box.tar.gz --strip-components=1 -C ./
          chmod +x sing-box

      - name: Generate geosite.dat
        run: |
          cd ${{ github.workspace }}/domain-list-community
          go run ./ --datapath=./data --outputname=geosite.dat \
            --outputdir=${{ github.workspace }}/dist --exportlists=category-ads-all,tld-cn,cn,tld-\!cn,geolocation-\!cn,apple,icloud

          cp ${{ github.workspace }}/dist/geosite.dat ${{ github.workspace }}/upload/

      - name: Generate geosite.db & rule-set
        run: |
          cd ${{ github.workspace }}/sing-geosite
          go run ./ --dat-in ${{ github.workspace }}/dist/geosite.dat --sdb-out ${{ github.workspace }}/upload/ --srs-out ${{ github.workspace }}/upload/

      - name: Export sing-box geosite rule-set json
        run: |
          cd ${{ github.workspace }}
          list=($(./sing-box geosite list -f ${{ github.workspace }}/upload/geosite.db | sed 's/ (.*)$//g'))
          echo "geosite node: ${#list[@]}"
          for ((i = 0; i < ${#list[@]}; i++)); do
            echo "write ${{ github.workspace }}/upload/rule-set/geosite-${list[i]}.json"
            ${{ github.workspace }}/sing-box geosite export ${list[i]} -f ${{ github.workspace }}/upload/geosite.db -o ${{ github.workspace }}/upload/rule-set/geosite-${list[i]}.json
          done

      - name: Generate geosite sha256 hash
        run: |
          cd ${{ github.workspace }}/upload/
          sha256sum geosite.dat > ${{ github.workspace }}/upload/geosite.dat.sha256sum
          sha256sum geosite.db > ${{ github.workspace }}/upload/geosite.db.sha256sum
          sha256sum geosite-cn.db > ${{ github.workspace }}/upload/geosite-cn.db.sha256sum

      - name: Push to "release" branch
        run: |
          mkdir -p ${{ github.workspace }}/release-upload/
          cp ${{ github.workspace }}/upload/geosite.db ${{ github.workspace }}/release-upload/
          cp ${{ github.workspace }}/upload/geosite.db.sha256sum ${{ github.workspace }}/release-upload/
          cp ${{ github.workspace }}/upload/geosite-cn.db ${{ github.workspace }}/release-upload/
          cp ${{ github.workspace }}/upload/geosite-cn.db.sha256sum ${{ github.workspace }}/release-upload/
          cp ${{ github.workspace }}/upload/geosite.dat ${{ github.workspace }}/release-upload/
          cp ${{ github.workspace }}/upload/geosite.dat.sha256sum ${{ github.workspace }}/release-upload/
          cd ${{ github.workspace }}/release-upload
          git init
          git config user.name "Epsilon"
          git config user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
          git checkout -b release
          git add .
          git commit -m "${{ env.TAG_NAME }}"
          git remote add origin "https://${{ github.actor }}:${{ github.token }}@github.com/${{ github.repository }}"
          git push -f origin release

      - name: Push to "rule-set" branch
        run: |
          mkdir -p ${{ github.workspace }}/rule-set-upload
          cp ${{ github.workspace }}/upload/rule-set/* ${{ github.workspace }}/rule-set-upload/
          cd ${{ github.workspace }}/rule-set-upload
          git init
          git config user.name "Epsilon"
          git config user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
          git checkout -b rule-set
          git add .
          git commit -m "${{ env.TAG_NAME }}"
          git remote add origin "https://${{ github.actor }}:${{ github.token }}@github.com/${{ github.repository }}"
          git push -f origin rule-set

      - name: Upload to Releases
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: ${{ env.TAG_NAME }}
          body: ${{ env.TAG_NAME }}
          draft: false
          prerelease: false
          files: |
            upload/geosite.dat*
            upload/geosite.db*
            upload/geosite-cn.db*

      - name: Remove old Releases
        uses: dev-drprasad/delete-older-releases@v0.3.3
        with:
          keep_latest: 3
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ github.token }}

      # - name: Upload to Latest Tag
      #   uses: softprops/action-gh-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ github.token }}
      #   with:
      #     tag_name: latest
      #     body: The latest.
      #     draft: false
      #     prerelease: true
      #     files: |
      #       upload/geosite.dat*
      #       upload/geosite.db*
      #       upload/geosite-cn.db*

      - name: Remove old Workflow runs records
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 3
          keep_minimum_runs: 3
